default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: myde_development
  
test:
  <<: *default
  database: myde_test

production:
  <<: *default
  database: dfj1cpd8l46e8g
  username: okcddhixelzrja
  password: po5JuNBe5twG0SK75H05SClGHM