default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: myde_development
  
test:
  <<: *default
  database: myde_test

production:
  <<: *default
  database: rails_project_production
  username: rails
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>