# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f594e0b95575a0e01c22f5d8b018c2fe82bfa55304b92a1942df993a448d2b1c728f3caa22b3b372a704e85d240cfec03306e63b14f0fdd5164657f92b3ae79

test:
  secret_key_base: 6aa7ab3c213845ace1b63dd51c421818bc4c067aaebf4652a4b8b0ed11557e3f2ace8d011104f9fb16fbb401aa5916991e4c90fd8b0c7b2e10d730957e56af50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
